class_name WorldStateDefinition
extends TarrockDefinition

## One row of the world-state matrix, as data.
##
## `docs/design/world.md` §World-state matrix is the SSOT for the permanent changes
## an unbinding makes to the world; every row there becomes one of these resources
## under `res://data/world_states/`, generated by `godot/tools/gen_definitions.py`
## and checked for drift by a test. The matrix also names the **branch** flags a
## quest's closing choice sets (the troupe's fate, which side of the Divide marries
## in); those get a definition of their own, tied to the row that mentions them.
##
## The definition carries no logic. `effect_summary` is the doc's own prose, kept so
## a reviewer can read the row without leaving the resource; what any of it *does*
## lives in whichever system subscribes to `WorldStateService.world_state_fired`.

## What kind of permanent change this flag records.
enum Kind {
	## An Arcana was unbound. Counts toward the act thresholds and appends to the
	## Fool's Reading.
	UNBINDING,
	## A quest choice picked one of a mutually exclusive set. Counts toward nothing.
	BRANCH,
}

## The shape every `WS_*` id has in `world.md`.
const ID_PATTERN := "^WS_[A-Z0-9_]+$"

## The lowest and highest card numbers an unbinding flag may carry (MQ01..MQ21).
const FIRST_ARCANA := 1
const LAST_ARCANA := 21

## Compiled once for the class: the drift tests validate every row in one pass.
static var _id_regex: RegEx = RegEx.create_from_string(ID_PATTERN)

## Whether this flag is an unbinding or one branch of a quest choice.
@export var kind: Kind = Kind.UNBINDING

## The quest that fires it, e.g. `&"MQ01"` - the matrix's "Fired by" column. For a
## branch flag, the quest whose choice sets it.
@export var fired_by: StringName = &""

## The card number this unbinding belongs to, 1..21; `0` for a branch flag.
@export var arcana_number: int = 0

## Branch flags only: the id of the mutually exclusive set this flag belongs to,
## e.g. `&"MQ01_TROUPE"`. "Exactly one member of a group is ever fired" is enforced
## by the quest runner (round 4), not by this definition and not by the service:
## the group is the data the runner needs to enforce it with
## (`WorldStateCatalog.branch_group_members()`).
@export var branch_group: StringName = &""

## The matrix's Effect column, verbatim. Documentation for reviewers, never logic.
@export var effect_summary: String = ""

## The doc section this row was generated from.
@export var doc_ref: String = ""


## Every problem with this row; empty means it matches the matrix's shape.
func validate() -> PackedStringArray:
	var errors := super()
	if id != &"" and _id_regex.search(String(id)) == null:
		errors.append("%s has an id that is not a WS_ flag: %s" % [_describe(), id])
	if fired_by == &"":
		errors.append("%s names no firing quest" % _describe())
	if kind == Kind.UNBINDING:
		if arcana_number < FIRST_ARCANA or arcana_number > LAST_ARCANA:
			errors.append("%s is an unbinding with card number %d, outside %d..%d" % [
				_describe(), arcana_number, FIRST_ARCANA, LAST_ARCANA
			])
		if branch_group != &"":
			errors.append("%s is an unbinding but names a branch group" % _describe())
	else:
		if branch_group == &"":
			errors.append("%s is a branch flag with no branch group" % _describe())
		if arcana_number != 0:
			errors.append("%s is a branch flag but carries card number %d" % [
				_describe(), arcana_number
			])
	return errors


## True when this flag counts toward the act thresholds and the Fool's Reading.
func is_unbinding() -> bool:
	return kind == Kind.UNBINDING
