class_name RegionIds
extends RefCounted

## Every region id and every Waystation id, as a constant.
##
## GENERATED by `godot/tools/gen_definitions.py` from `docs/design/world.md §Regions`
## - do not edit by hand; edit the doc and regenerate. A drift test fails when
## this file and `world.md` disagree.
##
## There are 22: the Cliff (0), which sits outside the Spread, and the twenty-one
## Arcana's regions (I-XXI). The tokens are the ones `SQ-<REGION>-<nn>` quest ids
## already use - the `docs/GLOSSARY.md` name, uppercased, article dropped.
##
## Code never types a region or Waystation id: it names one of these constants,
## or reads an id off a `RegionDefinition` (docs/design/technical.md, no magic
## strings). Where the Fool may go from where they are is NOT here - adjacency is
## hand-authored data in `res://data/regions/region_graph.tres`.

## The regions, in card order (the Cliff first, the Axis last).
const CLIFF := &"CLIFF"  # The Cliff
const PRESTIGE := &"PRESTIGE"  # The Prestige
const VEIL := &"VEIL"  # The Veil
const BOWER := &"BOWER"  # The Bower
const BASTION := &"BASTION"  # The Bastion
const CHANTRY := &"CHANTRY"  # The Chantry
const DIVIDE := &"DIVIDE"  # The Divide
const LONGROAD := &"LONGROAD"  # The Longroad
const MAW := &"MAW"  # The Maw
const DIM := &"DIM"  # The Dim
const WHEELHOUSE := &"WHEELHOUSE"  # The Wheelhouse
const ASSIZE := &"ASSIZE"  # The Assize
const GALLOWWOOD := &"GALLOWWOOD"  # The Gallowwood
const STILLMARSH := &"STILLMARSH"  # The Stillmarsh
const CONFLUENCE := &"CONFLUENCE"  # The Confluence
const UNDERVAULT := &"UNDERVAULT"  # The Undervault
const SPIRE := &"SPIRE"  # The Spire
const MERE := &"MERE"  # The Mere
const MIRRORMARSH := &"MIRRORMARSH"  # The Mirrormarsh
const NOONLANDS := &"NOONLANDS"  # The Noonlands
const HOLLOWS := &"HOLLOWS"  # The Hollows
const AXIS := &"AXIS"  # The Axis

## Every region `world.md` §Regions defines, in card order.
const ALL: Array[StringName] = [
	CLIFF,
	PRESTIGE,
	VEIL,
	BOWER,
	BASTION,
	CHANTRY,
	DIVIDE,
	LONGROAD,
	MAW,
	DIM,
	WHEELHOUSE,
	ASSIZE,
	GALLOWWOOD,
	STILLMARSH,
	CONFLUENCE,
	UNDERVAULT,
	SPIRE,
	MERE,
	MIRRORMARSH,
	NOONLANDS,
	HOLLOWS,
	AXIS,
]

## The Waystations, region by region. One per region, except the
## Longroad's network (`progression.md` §Waystations).
const WAYSTATION_CLIFF := &"WAYSTATION_CLIFF"
const WAYSTATION_PRESTIGE := &"WAYSTATION_PRESTIGE"
const WAYSTATION_VEIL := &"WAYSTATION_VEIL"
const WAYSTATION_BOWER := &"WAYSTATION_BOWER"
const WAYSTATION_BASTION := &"WAYSTATION_BASTION"
const WAYSTATION_CHANTRY := &"WAYSTATION_CHANTRY"
const WAYSTATION_DIVIDE := &"WAYSTATION_DIVIDE"
const WAYSTATION_LONGROAD_N := &"WAYSTATION_LONGROAD_N"
const WAYSTATION_LONGROAD_E := &"WAYSTATION_LONGROAD_E"
const WAYSTATION_LONGROAD_S := &"WAYSTATION_LONGROAD_S"
const WAYSTATION_LONGROAD_W := &"WAYSTATION_LONGROAD_W"
const WAYSTATION_MAW := &"WAYSTATION_MAW"
const WAYSTATION_DIM := &"WAYSTATION_DIM"
const WAYSTATION_WHEELHOUSE := &"WAYSTATION_WHEELHOUSE"
const WAYSTATION_ASSIZE := &"WAYSTATION_ASSIZE"
const WAYSTATION_GALLOWWOOD := &"WAYSTATION_GALLOWWOOD"
const WAYSTATION_STILLMARSH := &"WAYSTATION_STILLMARSH"
const WAYSTATION_CONFLUENCE := &"WAYSTATION_CONFLUENCE"
const WAYSTATION_UNDERVAULT := &"WAYSTATION_UNDERVAULT"
const WAYSTATION_SPIRE := &"WAYSTATION_SPIRE"
const WAYSTATION_MERE := &"WAYSTATION_MERE"
const WAYSTATION_MIRRORMARSH := &"WAYSTATION_MIRRORMARSH"
const WAYSTATION_NOONLANDS := &"WAYSTATION_NOONLANDS"
const WAYSTATION_HOLLOWS := &"WAYSTATION_HOLLOWS"
const WAYSTATION_AXIS := &"WAYSTATION_AXIS"

## Every Waystation in the Spread, in region order.
const WAYSTATIONS: Array[StringName] = [
	WAYSTATION_CLIFF,
	WAYSTATION_PRESTIGE,
	WAYSTATION_VEIL,
	WAYSTATION_BOWER,
	WAYSTATION_BASTION,
	WAYSTATION_CHANTRY,
	WAYSTATION_DIVIDE,
	WAYSTATION_LONGROAD_N,
	WAYSTATION_LONGROAD_E,
	WAYSTATION_LONGROAD_S,
	WAYSTATION_LONGROAD_W,
	WAYSTATION_MAW,
	WAYSTATION_DIM,
	WAYSTATION_WHEELHOUSE,
	WAYSTATION_ASSIZE,
	WAYSTATION_GALLOWWOOD,
	WAYSTATION_STILLMARSH,
	WAYSTATION_CONFLUENCE,
	WAYSTATION_UNDERVAULT,
	WAYSTATION_SPIRE,
	WAYSTATION_MERE,
	WAYSTATION_MIRRORMARSH,
	WAYSTATION_NOONLANDS,
	WAYSTATION_HOLLOWS,
	WAYSTATION_AXIS,
]
