class_name TrumpIds
extends RefCounted

## Every Trump id, as a constant.
##
## GENERATED by `godot/tools/gen_definitions.py` from every
## `**Trump N — Name.**` block in `docs/design/arcana.md` - do not edit by
## hand; edit the doc and regenerate. A drift test fails when this file and
## `arcana.md` disagree.
##
## There are exactly 20. `arcana.md` XXI: the World's card "is not carried. It
## is turned." - so the twenty-first Arcana yields no Trump.
##
## Code never types a Trump id: it names one of these constants, or reads an id
## off a `TrumpDefinition` (docs/design/technical.md, no magic strings).

## The Trumps, in card order (I first, XX last).
const TRUMP_01 := &"TRUMP_01"  # Manifest
const TRUMP_02 := &"TRUMP_02"  # Secrets
const TRUMP_03 := &"TRUMP_03"  # Bloom
const TRUMP_04 := &"TRUMP_04"  # Decree
const TRUMP_05 := &"TRUMP_05"  # Rite
const TRUMP_06 := &"TRUMP_06"  # Union
const TRUMP_07 := &"TRUMP_07"  # Triumph
const TRUMP_08 := &"TRUMP_08"  # Tame
const TRUMP_09 := &"TRUMP_09"  # Lantern
const TRUMP_10 := &"TRUMP_10"  # Spin
const TRUMP_11 := &"TRUMP_11"  # Verdict
const TRUMP_12 := &"TRUMP_12"  # Overturn
const TRUMP_13 := &"TRUMP_13"  # Passage
const TRUMP_14 := &"TRUMP_14"  # Blend
const TRUMP_15 := &"TRUMP_15"  # Bargain
const TRUMP_16 := &"TRUMP_16"  # Ruin
const TRUMP_17 := &"TRUMP_17"  # Wish
const TRUMP_18 := &"TRUMP_18"  # Glamour
const TRUMP_19 := &"TRUMP_19"  # Daybreak
const TRUMP_20 := &"TRUMP_20"  # Reveille

## Every Trump `arcana.md` defines, in card order.
const ALL: Array[StringName] = [
	TRUMP_01,
	TRUMP_02,
	TRUMP_03,
	TRUMP_04,
	TRUMP_05,
	TRUMP_06,
	TRUMP_07,
	TRUMP_08,
	TRUMP_09,
	TRUMP_10,
	TRUMP_11,
	TRUMP_12,
	TRUMP_13,
	TRUMP_14,
	TRUMP_15,
	TRUMP_16,
	TRUMP_17,
	TRUMP_18,
	TRUMP_19,
	TRUMP_20,
]
