class_name TrumpDefinition
extends TarrockDefinition

## One Trump: the card an unbound Arcana hands over, as data.
##
## `docs/design/arcana.md` is the SSOT for what each Trump does; every
## "**Trump N - Name.**" block there becomes one of these resources under
## `res://data/trumps/`, GENERATED by `godot/tools/gen_definitions.py` and checked
## for drift by a test. There are exactly twenty: XXI The World "is not carried, it
## is turned" (`arcana.md` §XXI), so the twenty-first Arcana yields no Trump.
##
## The generated half is identity and documentation: the card number, the name key,
## the world-state flag whose firing means the Fool holds this card, and the doc's
## own prose for each slot and for the reversed burden. The generator never writes
## the `effects` half - that is hand-authored under `res://data/trumps/effects/` and
## linked here when the file exists, exactly as a quest's authored graph is linked
## by its generated definition.
##
## **Holding is not stored anywhere.** A Trump is held when `granted_by_flag` has
## fired, and `WS_*` flags never un-fire (`WorldStateService`), so "which Trumps do
## I have" is derived from world state rather than duplicated into a second place
## that could disagree with it. `PocketSpreadService` does the deriving.

## The shape every Trump id has: `TRUMP_01` .. `TRUMP_20`.
const ID_PATTERN := "^TRUMP_[0-9]{2}$"

## The lowest and highest card numbers a Trump may carry. XXI yields no Trump.
const FIRST_TRUMP := 1
const LAST_TRUMP := 20

## Compiled once for the class: the drift tests validate every Trump in one pass.
static var _id_regex: RegEx = RegEx.create_from_string(ID_PATTERN)

## The Major Arcana number this Trump belongs to, 1..20 (I..XX).
@export var card_number: int = 0

## The translation key for the card's name, e.g. `&"TRUMP_01_NAME"` -> "Manifest".
## The English lives in `res://localization/trumps.csv` and nowhere else.
@export var name_key: StringName = &""

## The unbinding flag whose firing hands this Trump over, e.g.
## `&"WS_MAGICIAN_UNBOUND"`. It is the flag with this card's `arcana_number`, and it
## is the whole of "does the Fool hold this card".
@export var granted_by_flag: StringName = &""

## The Upright column of the doc's Past row, verbatim. Documentation for reviewers
## and for the drift test, never logic - the logic is `effects`.
@export var past_summary: String = ""

## The Upright column of the doc's Present row, verbatim.
@export var present_summary: String = ""

## The Upright column of the doc's Future row, verbatim.
@export var future_summary: String = ""

## The italicised name of the reversed burden, e.g. "the trick costs the trickster".
## Doc text for reviewers; the burden the game applies is `effects.burden`.
@export var burden_name: String = ""

## The doc's "Reversed burden" paragraph, verbatim.
@export var burden_summary: String = ""

## The doc section this Trump was generated from.
@export var doc_ref: String = ""

## The hand-authored six expressions and burden, or `null` when nobody has authored
## them yet. A Trump with none can still be held and slotted; its Present refuses to
## cast (see `TrumpEffects`).
@export var effects: TrumpEffects = null


## True when somebody has authored this Trump's six expressions.
func has_effects() -> bool:
	return effects != null


## The expression for one slot at one orientation, or `null` when unauthored.
func effect_for(slot: SpreadSlot.Id, orientation: CardOrientation.Id) -> TrumpEffect:
	if effects == null:
		return null
	return effects.for_slot(slot, orientation)


## The burden this card attaches when slotted reversed, or `null` when unauthored.
func burden() -> TrumpBurden:
	if effects == null:
		return null
	return effects.burden


## Every problem with this Trump; empty means it matches the doc's shape.
func validate() -> PackedStringArray:
	var errors := super()
	if id != &"" and _id_regex.search(String(id)) == null:
		errors.append("%s has an id that is no Trump id: %s" % [_describe(), id])
	if card_number < FIRST_TRUMP or card_number > LAST_TRUMP:
		errors.append("%s carries card number %d, outside %d..%d" % [
			_describe(), card_number, FIRST_TRUMP, LAST_TRUMP
		])
	if name_key == &"":
		errors.append("%s has no name key" % _describe())
	if granted_by_flag == &"":
		errors.append("%s names no unbinding flag that grants it" % _describe())
	for summary: String in [past_summary, present_summary, future_summary]:
		if summary.strip_edges().is_empty():
			errors.append("%s is missing one of its three slot summaries" % _describe())
	if burden_name.strip_edges().is_empty():
		errors.append("%s names no reversed burden" % _describe())
	if effects != null:
		errors.append_array(effects.validate())
	return errors
