extends TarrockTest

## `ReadingMotif` and `MotifCatalog`: the five starter motifs of `world.md` §The
## Fool's Reading, GENERATED by `tools/gen_definitions.py`, and the four `Rule`s a
## motif can evaluate against `WorldStateService.reading_order()`.
##
## The catalog itself is loaded for real (`res://data/npc/motifs/catalog.tres`) - this
## is the drift proxy `gen_definitions.py --check` cannot give a unit run: the .tres
## on disk, loaded through the engine, still names exactly the five doc rows and still
## validates clean. The RULE EVALUATION is exercised with synthetic reading orders,
## because a real reading takes twenty-one flags fired in a real playthrough to
## reach - the motif doesn't care whose flags they are, only their shape.

const MOTIF_CATALOG_PATH := "res://data/npc/motifs/catalog.tres"
const WORLD_STATE_CATALOG_PATH := "res://data/world_states/catalog.tres"

## The doc the five motifs are generated from, and the section heading the table sits
## under. Both are `gen_definitions.py`'s own (`READING_HEADING` there).
const WORLD_DOC_RELATIVE := "../docs/design/world.md"
const READING_HEADING := "## The Fool's Reading (sequence reactivity)"

var _catalog: MotifCatalog = null


func before_each() -> void:
	_catalog = load(MOTIF_CATALOG_PATH) as MotifCatalog


# --- The generated catalog itself --------------------------------------------


func test_the_catalog_carries_exactly_the_five_starter_motifs_in_doc_order() -> void:
	assert_eq(_catalog.ids(), MotifIds.ALL, "the catalog and MotifIds.ALL agree on the set and its order")


func test_the_generated_catalog_validates_clean() -> void:
	var world_states := load(WORLD_STATE_CATALOG_PATH) as WorldStateCatalog
	assert_eq(_catalog.validate(world_states), PackedStringArray())


func test_every_motif_carries_its_doc_cells_and_nothing_invented() -> void:
	for motif_id: StringName in MotifIds.ALL:
		var motif := _catalog.find(motif_id)
		if not assert_not_null(motif, "%s is in the catalog" % motif_id):
			continue
		assert_ne(motif.motif_summary, "", "%s carries the doc's Motif cell" % motif_id)
		assert_ne(motif.bark_flavor, "", "%s carries the doc's flavor cell" % motif_id)
		assert_ne(motif.doc_ref, "", "%s cites the doc" % motif_id)


# --- Drift: the .tres against `world.md`'s own table --------------------------


func test_the_generated_cells_are_still_the_docs_own() -> void:
	# The drift guard `gen_definitions.py --check` cannot give a unit run on its own:
	# it proves the generator would rewrite the same bytes, not that the bytes still
	# say what the doc says. So this reads §The Fool's Reading's table out of
	# `world.md` and compares both cells of all five rows against the loaded
	# resources - a canon edit that never reached the data is a red test here, not a
	# surprise in Act III.
	var rows := _doc_rows()
	if rows.is_empty():
		print("SKIP: %s is not present, so the motif table was not compared" % WORLD_DOC_RELATIVE)
		return
	if not assert_eq(rows.size(), MotifIds.ALL.size(), "the doc still lists five motifs"):
		return
	for index: int in rows.size():
		var row := rows[index]
		var motif := _catalog.find(MotifIds.ALL[index])
		if not assert_not_null(motif, "%s is in the catalog" % MotifIds.ALL[index]):
			continue
		assert_eq(motif.motif_summary, row[0], "row %d's Motif cell" % index)
		assert_eq(motif.bark_flavor, row[1], "row %d's flavor cell" % index)
		assert_true(
			motif.doc_ref.contains("world.md"),
			"%s cites the doc it was read from" % motif.id
		)


# --- Rule evaluation, against synthetic readings ------------------------------


func test_sun_before_star_selects_only_in_that_order() -> void:
	var motif := _catalog.find(MotifIds.MOTIF_SUN_BEFORE_STAR)
	var sun_first: Array[StringName] = [WorldStateIds.WS_SUN_UNBOUND, WorldStateIds.WS_STAR_UNBOUND]
	var star_first: Array[StringName] = [WorldStateIds.WS_STAR_UNBOUND, WorldStateIds.WS_SUN_UNBOUND]
	var sun_only: Array[StringName] = [WorldStateIds.WS_SUN_UNBOUND]
	assert_true(motif.matches(sun_first), "Sun really did come before Star")
	assert_false(motif.matches(star_first), "Star came first; the motif does not")
	assert_false(motif.matches(sun_only), "Star never unbound at all is not 'before' it")


func test_star_before_sun_is_the_mirror_motif() -> void:
	var motif := _catalog.find(MotifIds.MOTIF_STAR_BEFORE_SUN)
	var star_first: Array[StringName] = [WorldStateIds.WS_STAR_UNBOUND, WorldStateIds.WS_SUN_UNBOUND]
	var sun_first: Array[StringName] = [WorldStateIds.WS_SUN_UNBOUND, WorldStateIds.WS_STAR_UNBOUND]
	assert_true(motif.matches(star_first))
	assert_false(motif.matches(sun_first))


func test_death_in_act_i_is_the_first_seven_unbindings_only() -> void:
	var motif := _catalog.find(MotifIds.MOTIF_DEATH_IN_ACT_I)
	var death_seventh := _reading_with_death_at(6)  # index 6 = the 7th unbinding
	var death_eighth := _reading_with_death_at(7)  # index 7 = the 8th, into Act II
	assert_true(motif.matches(death_seventh), "Death as the 7th unbinding is still Act I")
	assert_false(motif.matches(death_eighth), "Death as the 8th unbinding is Act II")


func test_death_last_is_the_twentieth_unbinding_exactly() -> void:
	var motif := _catalog.find(MotifIds.MOTIF_DEATH_LAST)
	var death_twentieth := _reading_with_death_at(19)  # index 19 = the 20th
	var death_nineteenth := _reading_with_death_at(18)
	assert_true(motif.matches(death_twentieth))
	assert_false(motif.matches(death_nineteenth), "the 19th unbinding is not last of twenty")


func test_magician_not_first_needs_something_ahead_of_him() -> void:
	var motif := _catalog.find(MotifIds.MOTIF_MAGICIAN_NOT_FIRST)
	var magician_first: Array[StringName] = [WorldStateIds.WS_MAGICIAN_UNBOUND]
	var magician_second: Array[StringName] = [
		WorldStateIds.WS_PRIESTESS_UNBOUND, WorldStateIds.WS_MAGICIAN_UNBOUND
	]
	assert_false(motif.matches(magician_first), "first is exactly what this motif is not")
	assert_true(motif.matches(magician_second))


func test_an_unfired_flag_matches_nothing() -> void:
	var motif := _catalog.find(MotifIds.MOTIF_SUN_BEFORE_STAR)
	assert_false(motif.matches([]), "an empty Reading has no shape at all")


# --- Internals ---------------------------------------------------------------


## The Motif / Example-bark-flavor cells of §The Fool's Reading's table, in doc order,
## as `[motif, flavor]` per row. Empty when the doc is not beside the project (a source
## checkout without `docs/`), which the caller reports as a SKIP rather than a failure.
func _doc_rows() -> Array[PackedStringArray]:
	var rows: Array[PackedStringArray] = []
	var path := ProjectSettings.globalize_path("res://").path_join(WORLD_DOC_RELATIVE).simplify_path()
	if not FileAccess.file_exists(path):
		return rows
	var in_section := false
	for line: String in FileAccess.get_file_as_string(path).split("\n"):
		var trimmed := line.strip_edges()
		if trimmed == READING_HEADING:
			in_section = true
			continue
		if not in_section:
			continue
		if trimmed.begins_with("## "):
			break
		if not trimmed.begins_with("|"):
			continue
		var cells := PackedStringArray()
		for cell: String in trimmed.split("|"):
			var value := cell.strip_edges()
			if not value.is_empty():
				cells.append(value)
		if cells.size() != 2:
			continue
		if cells[0] == "Motif" or cells[0].begins_with("---"):
			continue
		rows.append(cells)
	return rows


## A synthetic reading `count` long, with `WS_DEATH_UNBOUND` at `death_index` and
## every other slot filled by a distinct placeholder flag - `matches()` only cares
## about `flag_a`'s position, never what the other entries are.
func _reading_with_death_at(death_index: int) -> Array[StringName]:
	var reading: Array[StringName] = []
	for index: int in range(20):
		if index == death_index:
			reading.append(WorldStateIds.WS_DEATH_UNBOUND)
		else:
			reading.append(StringName("WS_TEST_FILLER_%d" % index))
	return reading
