class_name EnemyDefinition
extends TarrockDefinition

## One enemy the game knows about: a Blank of a suit and a rank, or one of the two
## other families.
##
## GENERATED by `godot/tools/gen_definitions.py` from `docs/design/combat.md`
## §Enemies: the Blanks and §Other enemy families - fifty-two Blanks (four suits x
## thirteen ranks) under `res://data/enemies/blanks/`, plus `BEAST.tres` and
## `FOG_MASK.tres`. A drift test fails when this data and the doc disagree.
## `docs/design/technical.md` asks for exactly that shape: "one definition asset per
## suit/rank combination, one shared rig family".
##
## **It holds no numbers.** `combat.md` gives the Blanks two tables of ROLE and not
## one figure, so a stat block here would be a number somebody invented and then
## found in a resource six months later believing the doc had said it. Identity lives
## here; every number lives in `EnemyRules`; `stats()` is where they meet.
##
## The two `*_role_summary` fields are the doc's own table cells, verbatim. They are
## documentation and drift-check material, never logic and never displayed - the same
## job `TrumpDefinition.past_summary` does. What a suit or a rank actually DOES is
## `EnemyRules` and `BlankBrain`; if a summary and the code ever disagree, the doc
## decides and both are wrong.
##
## **Regional skins are not definitions.** `combat.md`: "Regional skins dress Blanks
## to match the region they're found in... cosmetic only; suit and rank still govern
## behavior". So a Bastion Blank is this definition with a different `sprite_family`
## chosen by the region, not a fifty-third row.

## The one sprite family every Blank shares. `combat.md`: "One base art and animation
## family carries every suit and rank".
const BLANK_SPRITE_FAMILY := &"blank"

## Which family this is. Only `BLANK` carries a suit and a rank.
@export var family: EnemyFamily.Id = EnemyFamily.Id.BLANK

## The suit, as a `Suit.Id`, or -1 for a family that has none.
@export var suit: int = -1

## The rank, as a `Rank.Id`, or -1 for a family that has none.
@export var rank: int = -1

## The shared art and animation family this enemy is drawn from.
@export var sprite_family: StringName = BLANK_SPRITE_FAMILY

## The suit's row in `combat.md`'s Combat role table, verbatim. Doc text.
@export var suit_role_summary: String = ""

## The rank's row in `combat.md`'s Role table, verbatim. Doc text.
@export var rank_role_summary: String = ""

## The whole bullet `combat.md` §Other enemy families gives this family, verbatim.
## Empty for the Blanks, whose two tables say it instead. Doc text.
@export var family_summary: String = ""

## The `WS_*` flag whose firing calms this family to neutral-until-provoked, or `&""`
## for a family nothing calms. `combat.md`: Beasts are "calmed to
## neutral-until-provoked world-wide once `WS_STRENGTH_UNBOUND` fires".
@export var calming_flag: StringName = &""

## The `WS_*` flag whose firing takes this family's ambush advantage away, or `&""`.
## `combat.md`: Fog-masks "lose their ambush advantage world-wide" once
## `WS_MOON_UNBOUND` fires.
@export var reveal_flag: StringName = &""

## The doc section this definition was generated from.
@export var doc_ref: String = ""

## The solved stat block, and the rules it was solved against. Derived, not authored:
## a definition is still immutable content (`TarrockDefinition`), and this is a cache
## of a pure function of it, keyed on its input so a different rules table cannot be
## served a stale answer.
var _stats: EnemyStats = null
var _stats_rules: EnemyRules = null


## The suit as a `Suit.Id`. Only meaningful when `has_suit_and_rank()`.
func suit_id() -> Suit.Id:
	return suit as Suit.Id


## The rank as a `Rank.Id`. Only meaningful when `has_suit_and_rank()`.
func rank_id() -> Rank.Id:
	return rank as Rank.Id


## True when this definition is one of the Blanks, so suit and rank mean something.
func has_suit_and_rank() -> bool:
	return EnemyFamily.has_suit_and_rank(family) and suit >= 0 and rank >= 0


## The side this enemy fights on.
func faction() -> Faction.Id:
	return EnemyFamily.faction_for(family)


## The number printed on this Blank's back, 2..10, or 0 for a court rank or another
## family. `combat.md` calls it "a simple visual tell of toughness".
func printed_number() -> int:
	if not has_suit_and_rank():
		return 0
	return Rank.printed_number(rank_id())


## This enemy's numbers, solved against a rules table.
##
## Cached per definition and keyed on the rules instance, so a fight that spawns
## fifty Blanks solves fifty stat blocks once each and nothing per frame. `null` when
## there are no rules, or when this definition is not a Blank - the Beast and
## Fog-mask stubs are identity and world-state only this round, and giving them
## invented numbers is exactly what this class refuses to do.
func stats(rules: EnemyRules) -> EnemyStats:
	if rules == null or not has_suit_and_rank():
		return null
	if _stats != null and _stats_rules == rules:
		return _stats
	_stats = _solve(rules)
	_stats_rules = rules
	return _stats


## Throw the cached stat block away. For a test that retunes a rules table in place;
## ordinary play builds a new table rather than editing one, because definitions and
## rules are both immutable content at runtime.
func clear_stats_cache() -> void:
	_stats = null
	_stats_rules = null


## Every problem with this definition; empty means it matches the doc's shape.
func validate() -> PackedStringArray:
	var errors := super()
	if family < 0 or family >= EnemyFamily.NAME_KEYS.size():
		errors.append("%s belongs to no enemy family" % _describe())
		return errors
	if sprite_family == &"":
		errors.append("%s names no sprite family to be drawn from" % _describe())
	if doc_ref.strip_edges().is_empty():
		errors.append("%s cites no doc section" % _describe())
	if EnemyFamily.has_suit_and_rank(family):
		errors.append_array(_validate_blank())
	else:
		errors.append_array(_validate_other_family())
	return errors


# --- Internals ----------------------------------------------------------------


## The checks only a Blank has to pass.
func _validate_blank() -> PackedStringArray:
	var errors := PackedStringArray()
	if suit < 0 or suit >= Suit.NAME_KEYS.size():
		errors.append("%s is a Blank of no suit" % _describe())
	if rank < 0 or rank >= Rank.NAME_KEYS.size():
		errors.append("%s is a Blank of no rank" % _describe())
	if sprite_family != BLANK_SPRITE_FAMILY:
		# `combat.md`: "One base art and animation family carries every suit and rank".
		errors.append("%s is a Blank drawn from %s rather than the one shared family" % [
			_describe(), sprite_family
		])
	if suit_role_summary.strip_edges().is_empty():
		errors.append("%s does not carry its suit's Combat role cell" % _describe())
	if rank_role_summary.strip_edges().is_empty():
		errors.append("%s does not carry its rank's Role cell" % _describe())
	if calming_flag != &"" or reveal_flag != &"":
		# Neither world-state rule in §Other enemy families is about the Blanks.
		errors.append("%s is a Blank gated on a world-state flag, which no Blank is" % _describe())
	var expected := StringName(
		"BLANK_%s_%s" % [Suit.name_key(suit as Suit.Id), Rank.name_key(rank as Rank.Id)]
	)
	if id != expected:
		errors.append("%s is called %s but its suit and rank spell %s" % [
			_describe(), id, expected
		])
	return errors


## The checks a Beast or a Fog-mask has to pass.
func _validate_other_family() -> PackedStringArray:
	var errors := PackedStringArray()
	if suit >= 0 or rank >= 0:
		errors.append("%s is not a Blank, so it can have no suit and no rank" % _describe())
	if family_summary.strip_edges().is_empty():
		errors.append("%s does not carry its family's own paragraph" % _describe())
	if family == EnemyFamily.Id.BEAST and calming_flag == &"":
		errors.append("%s is a Beast nothing calms; combat.md says a flag does" % [_describe()])
	if family == EnemyFamily.Id.FOG_MASK and reveal_flag == &"":
		errors.append("%s is a Fog-mask nothing reveals; combat.md says a flag does" % [
			_describe()
		])
	if id != EnemyFamily.name_key(family):
		errors.append("%s is called %s but its family is %s" % [
			_describe(), id, EnemyFamily.name_key(family)
		])
	return errors


## Multiply the identity by the rules. Pure, and called once per definition.
func _solve(rules: EnemyRules) -> EnemyStats:
	var solved := EnemyStats.new()
	var own_suit := suit_id()
	var own_rank := rank_id()
	solved.max_health = maxi(
		1, int(roundf(float(rules.health_for_suit(own_suit)) * rules.health_multiplier_for_rank(own_rank)))
	)
	solved.damage = maxi(
		1, int(roundf(float(rules.damage_for_suit(own_suit)) * rules.damage_multiplier_for_rank(own_rank)))
	)
	solved.move_speed = rules.move_speed_for_suit(own_suit) * rules.speed_multiplier_for_rank(own_rank)
	solved.telegraph_seconds = (
		rules.telegraph_for_suit(own_suit) * rules.telegraph_multiplier_for_rank(own_rank)
	)
	solved.active_seconds = rules.active_for_suit(own_suit)
	solved.recovery_seconds = rules.recovery_for_suit(own_suit)
	solved.attack_arc_degrees = rules.attack_arc_for_suit(own_suit)
	solved.attack_radius = rules.attack_radius_for_suit(own_suit)
	solved.string_length = rules.string_length_for_suit(own_suit)
	solved.followup_telegraph_multiplier = rules.swords_followup_telegraph_multiplier
	solved.is_ranged = rules.is_ranged_suit(own_suit)
	if solved.is_ranged:
		solved.projectile_speed = rules.cups_projectile_speed
		solved.projectile_radius = rules.cups_projectile_radius
		solved.preferred_range = rules.cups_preferred_range
		solved.projectile_life_seconds = (
			solved.attack_radius / maxf(solved.projectile_speed, 1.0)
			+ rules.cups_projectile_extra_life_seconds
		)
	solved.has_shield = rules.is_shielded_suit(own_suit)
	if solved.has_shield:
		solved.block_arc_degrees = rules.coins_block_arc_degrees
		solved.block_chance = rules.coins_block_chance
		solved.armour_multiplier = rules.coins_armour_multiplier
	solved.hit_tag = rules.tag_for_suit(own_suit)
	if solved.hit_tag != &"":
		solved.hit_tag_seconds = rules.wands_fire_lingering_seconds
	solved.aggro_radius = rules.aggro_radius
	solved.disengage_radius = rules.disengage_radius
	solved.aware_seconds = rules.aware_seconds
	solved.flees_to_alert = Rank.flees_to_alert(own_rank)
	if solved.flees_to_alert:
		solved.alert_radius = rules.page_alert_radius
		solved.alert_seconds = rules.page_alert_seconds
	solved.grants_aura = Rank.grants_aura(own_rank)
	if solved.grants_aura:
		solved.aura_radius = rules.queen_aura_radius
		solved.aura_damage_multiplier = rules.queen_aura_damage_multiplier
		solved.aura_telegraph_multiplier = rules.queen_aura_telegraph_multiplier
	solved.card_flutter_seconds = rules.card_flutter_seconds
	return solved
