class_name MotifIds
extends RefCounted

## Every motif of the Fool's Reading, as a constant.
##
## GENERATED by `godot/tools/gen_definitions.py` from
## `docs/design/world.md §The Fool's Reading (sequence reactivity)`'s
## starter-motif table - do not edit by hand; edit the doc and regenerate. A
## drift test fails when this file and the table disagree.
##
## A motif is a SHAPE the Reading can have - Sun before Star, Death early,
## the Magician not first - and `npc-system.md` §Bark layers puts the barks
## that wait on one at layer 2. The rule each motif evaluates is hand-mapped
## in the generator (`MOTIFS_BY_ROW`) and carried in the `.tres`; this file
## is only the ids.
##
## Code never types a motif id: it names one of these constants, or reads an
## id off a `ReadingMotif` (docs/design/technical.md, no magic strings).

## The motifs, in the doc's own row order.
const MOTIF_SUN_BEFORE_STAR := &"MOTIF_SUN_BEFORE_STAR"  # Sun unbound before Star
const MOTIF_STAR_BEFORE_SUN := &"MOTIF_STAR_BEFORE_SUN"  # Star unbound before Sun
const MOTIF_DEATH_IN_ACT_I := &"MOTIF_DEATH_IN_ACT_I"  # Death unbound in Act I (first 7)
const MOTIF_DEATH_LAST := &"MOTIF_DEATH_LAST"  # Death unbound last of the 20
const MOTIF_MAGICIAN_NOT_FIRST := &"MOTIF_MAGICIAN_NOT_FIRST"  # Magician not first

## Every motif the table defines, in row order.
const ALL: Array[StringName] = [
	MOTIF_SUN_BEFORE_STAR,
	MOTIF_STAR_BEFORE_SUN,
	MOTIF_DEATH_IN_ACT_I,
	MOTIF_DEATH_LAST,
	MOTIF_MAGICIAN_NOT_FIRST,
]
