class_name DeedIds
extends RefCounted

## Every deed id, as a constant.
##
## GENERATED by `godot/tools/gen_definitions.py` from
## `docs/design/progression.md §Renown`'s deed table - do not edit by hand; edit
## the doc and regenerate. A drift test fails when this file and the table
## disagree.
##
## A deed is a KIND of deed, not one occurrence: the doc's rows are examples of
## the sort of thing each suit-culture notices, and a quest that wants Renown to
## move names the row it is an instance of. `EconomyService.record_deed()` is the
## only thing that reads one, and the only place a deed becomes Renown.
##
## Code never types a deed id: it names one of these constants, or reads an id
## off a `DeedDefinition` (docs/design/technical.md, no magic strings).

## The deeds, in the doc's own row order.
const DEED_HELP_A_STRANGER := &"DEED_HELP_A_STRANGER"  # Helping a stranger at personal cost
const DEED_WIN_A_DUEL := &"DEED_WIN_A_DUEL"  # Winning a formal duel or contest
const DEED_SHARP_BARGAIN := &"DEED_SHARP_BARGAIN"  # Striking a sharp bargain
const DEED_FINISH_A_CRAFT := &"DEED_FINISH_A_CRAFT"  # Finishing a craft or creative work

## Every deed the table defines, in row order.
const ALL: Array[StringName] = [
	DEED_HELP_A_STRANGER,
	DEED_WIN_A_DUEL,
	DEED_SHARP_BARGAIN,
	DEED_FINISH_A_CRAFT,
]
