class_name DeedDefinition
extends TarrockDefinition

## One row of `docs/design/progression.md` §Renown's deed table: a kind of deed, and
## what each of the four suit-cultures makes of it.
##
## GENERATED by `godot/tools/gen_definitions.py` into
## `res://data/progression/deeds/` - do not edit by hand; edit the doc and
## regenerate. A drift test fails when this file and §Renown disagree.
##
## The doc's own point is the one thing this class must not lose: **Renown is not a
## morality meter.** There is no overall good/bad number on a deed - there are four
## opinions, and the same act raises the Fool with one culture while it costs them
## standing with another (helping a stranger at personal cost is hospitality to Cups
## and bad business to Coins). So a deed carries four independent reactions and no
## summary of them, and nothing anywhere adds them up.
##
## The **magnitudes are not here** either: §Renown states reactions and no numbers.
## `EconomyRules.renown_delta_for()` turns a reaction into points, and
## `EconomyService.record_deed()` is the only thing that spends it.

## The deed's own cell in the doc's table, verbatim. Doc-only: it is what a reviewer
## and the drift test compare against, and nothing displays it.
@export var deed_summary: String = ""

## What Cups makes of the deed.
@export var reaction_cups: Reaction.Id = Reaction.Id.NEUTRAL

## What Swords makes of it.
@export var reaction_swords: Reaction.Id = Reaction.Id.NEUTRAL

## What Wands makes of it.
@export var reaction_wands: Reaction.Id = Reaction.Id.NEUTRAL

## What Coins makes of it.
@export var reaction_coins: Reaction.Id = Reaction.Id.NEUTRAL

## The parenthetical reason Cups' cell gives, verbatim and without its brackets, or
## `""` when the cell gives none. Doc-only, like `deed_summary`.
@export var reaction_note_cups: String = ""

## The same for Swords' cell. Doc-only.
@export var reaction_note_swords: String = ""

## The same for Wands' cell. Doc-only.
@export var reaction_note_wands: String = ""

## The same for Coins' cell. Doc-only.
@export var reaction_note_coins: String = ""

## The doc section this row was generated from. Doc-only.
@export var doc_ref: String = ""


## What one suit makes of this deed.
func reaction_for(suit: Suit.Id) -> Reaction.Id:
	match suit:
		Suit.Id.CUPS:
			return reaction_cups
		Suit.Id.SWORDS:
			return reaction_swords
		Suit.Id.WANDS:
			return reaction_wands
		Suit.Id.COINS:
			return reaction_coins
	return Reaction.Id.NEUTRAL


## The doc's parenthetical reason for one suit's reaction, or `""`. Doc-only.
func reaction_note_for(suit: Suit.Id) -> String:
	match suit:
		Suit.Id.CUPS:
			return reaction_note_cups
		Suit.Id.SWORDS:
			return reaction_note_swords
		Suit.Id.WANDS:
			return reaction_note_wands
		Suit.Id.COINS:
			return reaction_note_coins
	return ""


## True when at least one suit cares. A deed every culture shrugs at is a deed that
## does nothing, which is a doc row somebody mis-transcribed rather than a design.
func moves_anyone() -> bool:
	for suit: Suit.Id in Suit.ALL:
		if reaction_for(suit) != Reaction.Id.NEUTRAL:
			return true
	return false


## Every problem with this deed; empty means it matches a readable doc row.
func validate() -> PackedStringArray:
	var errors := super()
	if deed_summary.strip_edges().is_empty():
		errors.append("%s carries no deed text" % _describe())
	for suit: Suit.Id in Suit.ALL:
		var reaction := reaction_for(suit)
		if reaction < 0 or reaction >= Reaction.ALL.size():
			errors.append("%s reacts %d for %s" % [
				_describe(), reaction, Suit.name_key(suit)
			])
	if not moves_anyone():
		errors.append("%s leaves every suit unmoved" % _describe())
	return errors
