class_name RegionDefinition
extends TarrockDefinition

## One region of the Spread: the Cliff, or one of the twenty-one Arcana's places.
##
## GENERATED by `godot/tools/gen_definitions.py` from `docs/design/world.md` §Regions
## (one bullet per region), §Intended difficulty bands and the world-state matrix -
## one `.tres` per bullet under `res://data/regions/`. A drift test fails when this
## data and the doc disagree.
##
## **The LIST is generated; the ADJACENCY is not.** `world.md` §Layout draws the wheel
## as an ASCII diagram, which no parser can read as a graph without inventing edges
## nobody wrote down. So who touches whom is hand-authored in
## `res://data/regions/region_graph.tres` (`RegionGraph`), which cites §Layout and is
## reviewed against the diagram by a human. A definition therefore carries no
## adjacency list of its own: there is one graph, in one file, and a region cannot
## disagree with it.
##
## `summary` is the doc's own bullet, verbatim. It is documentation and drift-check
## material, never logic and never displayed - the same job `TrumpDefinition`'s slot
## summaries do. What a region IS to the player is its scene and its quests; if a
## summary and the game ever disagree, the doc decides and the game is wrong.

## The card number: 0 for the Cliff, 1-21 for the Arcana whose region this is.
## `world.md` §Regions writes it in the bullet's own parenthesis.
@export var card_number: int = 0

## The translation key the region's name resolves through
## (`localization/regions.csv`). The English is the `docs/GLOSSARY.md` name, article
## and all: "The Mirrormarsh", never "Mirrormarsh".
@export var name_key: StringName = &""

## The `WS_*` flag that means this region's Arcana is unbound and the place is awake -
## the flag the White Rose asks about to know whether it may regrow here
## (`docs/design/progression.md` §The White Rose). `&""` for the Cliff, which has no
## Arcana and no unbinding of its own, and where the Rose therefore never regrows.
@export var unbinding_flag: StringName = &""

## Which of `world.md`'s soft difficulty bands this region is tuned for. Never a gate:
## see `DifficultyBand`.
@export var difficulty_band: DifficultyBand.Id = DifficultyBand.Id.NONE

## The region's whole bullet from `world.md` §Regions, verbatim. Doc text.
@export var summary: String = ""

## The scene this region loads as. It may not exist yet - twenty of the twenty-two are
## unbuilt - and `has_scene()` is how `RegionService` refuses to travel somewhere the
## game cannot draw instead of loading nothing and leaving the Fool nowhere.
@export var scene_path: String = ""

## The Waystations authored in this region, by id (`WAYSTATION_<REGION>` for the one
## every region has; the Longroad's network carries a compass suffix each). Ids only:
## the nodes themselves live in the region scene, which is where a rest actually
## happens (`docs/design/technical.md` §Regions and the persistent layer).
@export var waystation_ids: Array[StringName] = []

## The doc section this definition was generated from.
@export var doc_ref: String = ""


## True when this region's scene file exists in the project.
##
## Asked before every travel, and false for every region nobody has greyboxed yet.
## The refusal is a `RegionService.REASON_NO_SCENE`, which is a developer diagnostic
## and never a player-facing message: by the time a player can walk anywhere, a
## missing scene is a bug, not a locked door.
func has_scene() -> bool:
	return scene_path != "" and ResourceLoader.exists(scene_path)


## True for the Cliff: card 0, no Arcana, outside the Spread (`world.md` §The Spread).
func is_the_cliff() -> bool:
	return card_number == 0


## True when this region's Arcana has been unbound, and the place is therefore awake.
## The one question the White Rose's regrowth rule turns on.
func is_unbound(world_state: WorldStateService) -> bool:
	if unbinding_flag == &"" or world_state == null:
		return false
	return world_state.is_fired(unbinding_flag)


## The Waystation this region's `WAYSTATION_<REGION>` id names - its first, and for
## every region but the Longroad its only one. `&""` for a region with none.
func first_waystation_id() -> StringName:
	if waystation_ids.is_empty():
		return &""
	return waystation_ids[0]


## True when this region authors a Waystation with this id.
func has_waystation(waystation_id: StringName) -> bool:
	return waystation_ids.has(waystation_id)


## Every problem with this definition, one string per problem.
func validate() -> PackedStringArray:
	var errors := super()
	if card_number < 0 or card_number > 21:
		errors.append("%s has card number %d, which is not 0-21" % [id, card_number])
	if name_key == &"":
		errors.append("%s has no name key" % id)
	if scene_path == "":
		errors.append("%s has no scene path" % id)
	if is_the_cliff():
		if unbinding_flag != &"":
			errors.append("the Cliff has no Arcana, so it cannot have %s" % unbinding_flag)
		if difficulty_band != DifficultyBand.Id.NONE:
			errors.append("the Cliff is outside the Spread and has no difficulty band")
	else:
		if unbinding_flag == &"":
			errors.append("%s is an Arcana's region and names no unbinding flag" % id)
		if not DifficultyBand.is_banded(difficulty_band):
			errors.append("%s is in no difficulty band" % id)
	if waystation_ids.is_empty():
		errors.append("%s has no Waystation; every region has at least one" % id)
	var seen: Dictionary = {}
	for waystation_id: StringName in waystation_ids:
		if seen.has(waystation_id):
			errors.append("%s lists the Waystation %s twice" % [id, waystation_id])
		seen[waystation_id] = true
	if doc_ref == "":
		errors.append("%s does not say which doc section it came from" % id)
	return errors
